# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class VirtualDirectory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'listener_policy': 'str',
        'remote_policy': 'str',
        'virtual_path': 'str',
        'remote_path': 'str',
        'alt_protocol': 'str',
        'alt_host': 'str',
        'alt_port': 'int',
        'virtual_host': 'str',
        'enabled': 'bool',
        'use_alt_location': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'listener_policy': 'listenerPolicy',
        'remote_policy': 'remotePolicy',
        'virtual_path': 'virtualPath',
        'remote_path': 'remotePath',
        'alt_protocol': 'altProtocol',
        'alt_host': 'altHost',
        'alt_port': 'altPort',
        'virtual_host': 'virtualHost',
        'enabled': 'enabled',
        'use_alt_location': 'useAltLocation'
    }

    def __init__(self, name=None, description=None, listener_policy=None, remote_policy=None, virtual_path=None, remote_path=None, alt_protocol=None, alt_host=None, alt_port=None, virtual_host=None, enabled=None, use_alt_location=None):  # noqa: E501
        """VirtualDirectory - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._description = None
        self._listener_policy = None
        self._remote_policy = None
        self._virtual_path = None
        self._remote_path = None
        self._alt_protocol = None
        self._alt_host = None
        self._alt_port = None
        self._virtual_host = None
        self._enabled = None
        self._use_alt_location = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if listener_policy is not None:
            self.listener_policy = listener_policy
        if remote_policy is not None:
            self.remote_policy = remote_policy
        if virtual_path is not None:
            self.virtual_path = virtual_path
        if remote_path is not None:
            self.remote_path = remote_path
        if alt_protocol is not None:
            self.alt_protocol = alt_protocol
        if alt_host is not None:
            self.alt_host = alt_host
        if alt_port is not None:
            self.alt_port = alt_port
        if virtual_host is not None:
            self.virtual_host = virtual_host
        if enabled is not None:
            self.enabled = enabled
        if use_alt_location is not None:
            self.use_alt_location = use_alt_location

    @property
    def name(self):
        """Gets the name of this VirtualDirectory.  # noqa: E501


        :return: The name of this VirtualDirectory.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VirtualDirectory.


        :param name: The name of this VirtualDirectory.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this VirtualDirectory.  # noqa: E501


        :return: The description of this VirtualDirectory.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this VirtualDirectory.


        :param description: The description of this VirtualDirectory.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def listener_policy(self):
        """Gets the listener_policy of this VirtualDirectory.  # noqa: E501


        :return: The listener_policy of this VirtualDirectory.  # noqa: E501
        :rtype: str
        """
        return self._listener_policy

    @listener_policy.setter
    def listener_policy(self, listener_policy):
        """Sets the listener_policy of this VirtualDirectory.


        :param listener_policy: The listener_policy of this VirtualDirectory.  # noqa: E501
        :type: str
        """

        self._listener_policy = listener_policy

    @property
    def remote_policy(self):
        """Gets the remote_policy of this VirtualDirectory.  # noqa: E501


        :return: The remote_policy of this VirtualDirectory.  # noqa: E501
        :rtype: str
        """
        return self._remote_policy

    @remote_policy.setter
    def remote_policy(self, remote_policy):
        """Sets the remote_policy of this VirtualDirectory.


        :param remote_policy: The remote_policy of this VirtualDirectory.  # noqa: E501
        :type: str
        """

        self._remote_policy = remote_policy

    @property
    def virtual_path(self):
        """Gets the virtual_path of this VirtualDirectory.  # noqa: E501


        :return: The virtual_path of this VirtualDirectory.  # noqa: E501
        :rtype: str
        """
        return self._virtual_path

    @virtual_path.setter
    def virtual_path(self, virtual_path):
        """Sets the virtual_path of this VirtualDirectory.


        :param virtual_path: The virtual_path of this VirtualDirectory.  # noqa: E501
        :type: str
        """

        self._virtual_path = virtual_path

    @property
    def remote_path(self):
        """Gets the remote_path of this VirtualDirectory.  # noqa: E501


        :return: The remote_path of this VirtualDirectory.  # noqa: E501
        :rtype: str
        """
        return self._remote_path

    @remote_path.setter
    def remote_path(self, remote_path):
        """Sets the remote_path of this VirtualDirectory.


        :param remote_path: The remote_path of this VirtualDirectory.  # noqa: E501
        :type: str
        """

        self._remote_path = remote_path

    @property
    def alt_protocol(self):
        """Gets the alt_protocol of this VirtualDirectory.  # noqa: E501


        :return: The alt_protocol of this VirtualDirectory.  # noqa: E501
        :rtype: str
        """
        return self._alt_protocol

    @alt_protocol.setter
    def alt_protocol(self, alt_protocol):
        """Sets the alt_protocol of this VirtualDirectory.


        :param alt_protocol: The alt_protocol of this VirtualDirectory.  # noqa: E501
        :type: str
        """
        allowed_values = ["", "http", "https"]  # noqa: E501
        if alt_protocol not in allowed_values:
            raise ValueError(
                "Invalid value for `alt_protocol` ({0}), must be one of {1}"  # noqa: E501
                .format(alt_protocol, allowed_values)
            )

        self._alt_protocol = alt_protocol

    @property
    def alt_host(self):
        """Gets the alt_host of this VirtualDirectory.  # noqa: E501


        :return: The alt_host of this VirtualDirectory.  # noqa: E501
        :rtype: str
        """
        return self._alt_host

    @alt_host.setter
    def alt_host(self, alt_host):
        """Sets the alt_host of this VirtualDirectory.


        :param alt_host: The alt_host of this VirtualDirectory.  # noqa: E501
        :type: str
        """

        self._alt_host = alt_host

    @property
    def alt_port(self):
        """Gets the alt_port of this VirtualDirectory.  # noqa: E501


        :return: The alt_port of this VirtualDirectory.  # noqa: E501
        :rtype: int
        """
        return self._alt_port

    @alt_port.setter
    def alt_port(self, alt_port):
        """Sets the alt_port of this VirtualDirectory.


        :param alt_port: The alt_port of this VirtualDirectory.  # noqa: E501
        :type: int
        """

        self._alt_port = alt_port

    @property
    def virtual_host(self):
        """Gets the virtual_host of this VirtualDirectory.  # noqa: E501


        :return: The virtual_host of this VirtualDirectory.  # noqa: E501
        :rtype: str
        """
        return self._virtual_host

    @virtual_host.setter
    def virtual_host(self, virtual_host):
        """Sets the virtual_host of this VirtualDirectory.


        :param virtual_host: The virtual_host of this VirtualDirectory.  # noqa: E501
        :type: str
        """

        self._virtual_host = virtual_host

    @property
    def enabled(self):
        """Gets the enabled of this VirtualDirectory.  # noqa: E501


        :return: The enabled of this VirtualDirectory.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this VirtualDirectory.


        :param enabled: The enabled of this VirtualDirectory.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def use_alt_location(self):
        """Gets the use_alt_location of this VirtualDirectory.  # noqa: E501


        :return: The use_alt_location of this VirtualDirectory.  # noqa: E501
        :rtype: bool
        """
        return self._use_alt_location

    @use_alt_location.setter
    def use_alt_location(self, use_alt_location):
        """Sets the use_alt_location of this VirtualDirectory.


        :param use_alt_location: The use_alt_location of this VirtualDirectory.  # noqa: E501
        :type: bool
        """

        self._use_alt_location = use_alt_location

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VirtualDirectory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
