# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import forumsentry_api
from forumsentry_api.api.policieskey_pairs_api import PolicieskeyPairsApi  # noqa: E501
from forumsentry_api.rest import ApiException


class TestPolicieskeyPairsApi(unittest.TestCase):
    """PolicieskeyPairsApi unit test stubs"""

    def setUp(self):
        self.api = forumsentry_api.api.policieskey_pairs_api.PolicieskeyPairsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_policy_list(self):
        """Test case for get_policy_list

        returns a list of policies  # noqa: E501
        """
        pass

    def test_import_jks_store(self):
        """Test case for import_jks_store

        import Java Key Store (JKS) File  # noqa: E501
        """
        pass

    def test_import_pkcs12(self):
        """Test case for import_pkcs12

        import PKCS#12 key pairs  # noqa: E501
        """
        pass

    def test_import_pkcs1_or_pkcs8(self):
        """Test case for import_pkcs1_or_pkcs8

        import PKCS#1 or PKCS#8 key pairs  # noqa: E501
        """
        pass

    def test_import_x509_or7_file(self):
        """Test case for import_x509_or7_file

        import X.509 OR PKCS#7 public certificates  # noqa: E501
        """
        pass

    def test_import_x509_or7_ldap(self):
        """Test case for import_x509_or7_ldap

        import X.509 OR PKCS#7 public certificates with LDAP  # noqa: E501
        """
        pass

    def test_remove_policy(self):
        """Test case for remove_policy

        deletes the policy  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
