# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import forumsentry_api
from forumsentry_api.models.sun_mq_remote_policy1 import SunMqRemotePolicy1  # noqa: E501
from forumsentry_api.rest import ApiException


class TestSunMqRemotePolicy1(unittest.TestCase):
    """SunMqRemotePolicy1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSunMqRemotePolicy1(self):
        """Test SunMqRemotePolicy1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = forumsentry_api.models.sun_mq_remote_policy1.SunMqRemotePolicy1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
