# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest
import string
import random

import forumsentry_api
from forumsentry_api.models.http_listener_policy import HttpListenerPolicy  # noqa: E501


class TestHttpListenerPolicy(unittest.TestCase):
    """HttpListenerPolicy unit test stubs"""

    def id_generator(self, size=6, chars=string.ascii_uppercase + string.digits):
        return ''.join(random.choice(chars) for _ in range(size))

    def setUp(self):
        self._test_id = self.id_generator()
        pass

    def tearDown(self):
        pass

    def testHttpListenerPolicy(self):
        """Test HttpListenerPolicy"""
        # FIXME: construct object with mandatory attributes with example values
        model = HttpListenerPolicy()  # noqa: E501
        model.name = self._test_id
        
        
        pass


if __name__ == '__main__':
    unittest.main()
