# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import forumsentry_api
from forumsentry_api.api.policieslogging_configurations_api import PoliciesloggingConfigurationsApi  # noqa: E501
from forumsentry_api.rest import ApiException


class TestPoliciesloggingConfigurationsApi(unittest.TestCase):
    """PoliciesloggingConfigurationsApi unit test stubs"""

    def setUp(self):
        self.api = forumsentry_api.api.policieslogging_configurations_api.PoliciesloggingConfigurationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_export_fsg(self):
        """Test case for export_fsg

        exports an fsg based on this policy to a file  # noqa: E501
        """
        pass

    def test_get_policy(self):
        """Test case for get_policy

        gets the Logging  # noqa: E501
        """
        pass

    def test_get_policy_list(self):
        """Test case for get_policy_list

        returns a list of policies  # noqa: E501
        """
        pass

    def test_transfer_fsg(self):
        """Test case for transfer_fsg

        transfers an fsg based on this policy to the specified agent group  # noqa: E501
        """
        pass

    def test_update_policy(self):
        """Test case for update_policy

        updates the Logging  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
