# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import forumsentry_api
from .policiesxml_policies_api import PoliciesxmlPoliciesApi  # noqa: E501
from forumsentry_api.rest import ApiException


class TestPoliciesxmlPoliciesApi(unittest.TestCase):
    """PoliciesxmlPoliciesApi unit test stubs"""

    def setUp(self):
        self.api = .policiesxml_policies_api.PoliciesxmlPoliciesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_fs_project_node_copy(self):
        """Test case for create_fs_project_node_copy

        creates a copy of the policy  # noqa: E501
        """
        pass

    def test_create_or_update_policy(self):
        """Test case for create_or_update_policy

        creates or updates the policy  # noqa: E501
        """
        pass

    def test_create_or_update_policy_0(self):
        """Test case for create_or_update_policy_0

        creates or updates the virtual directory  # noqa: E501
        """
        pass

    def test_create_policy(self):
        """Test case for create_policy

        creates a new policy  # noqa: E501
        """
        pass

    def test_create_policy_0(self):
        """Test case for create_policy_0

        creates a new virtual directory  # noqa: E501
        """
        pass

    def test_export_fsg(self):
        """Test case for export_fsg

        exports an fsg based on this policy to a file  # noqa: E501
        """
        pass

    def test_get_policy(self):
        """Test case for get_policy

        gets the policy  # noqa: E501
        """
        pass

    def test_get_policy_0(self):
        """Test case for get_policy_0

        gets the virtual directory  # noqa: E501
        """
        pass

    def test_get_policy_list(self):
        """Test case for get_policy_list

        returns a list of policies  # noqa: E501
        """
        pass

    def test_get_policy_list_0(self):
        """Test case for get_policy_list_0

        returns a list of this policy's virtual directories  # noqa: E501
        """
        pass

    def test_remove_policy(self):
        """Test case for remove_policy

        deletes the policy  # noqa: E501
        """
        pass

    def test_remove_policy_0(self):
        """Test case for remove_policy_0

        deletes the virtual directory  # noqa: E501
        """
        pass

    def test_transfer_fsg(self):
        """Test case for transfer_fsg

        transfers an fsg based on this policy to the specified agent group  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
