# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import forumsentry_api
from forumsentry_api.models.wsdl_policy import WsdlPolicy  # noqa: E501
from forumsentry_api.rest import ApiException


class TestWsdlPolicy(unittest.TestCase):
    """WsdlPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWsdlPolicy(self):
        """Test WsdlPolicy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = forumsentry_api.models.wsdl_policy.WsdlPolicy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
