Quickstart
----------

.. toctree::
    :maxdepth: 2

    quickstart

Tutorial
--------

Coming soon.

API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
    :maxdepth: 2

    api


Models Reference
-------------

List of models which are currently supported

.. toctree::
    :maxdepth: 2

    models


Developer Documentation
-----------------------

.. toctree::
    :maxdepth: 2

    dev 

Changelog
---------

.. toctree::
    :maxdepth: 3

    changelog

Attribution
-----------

* This project relies on the wonderful `requests <http://docs.python-requests.org/en/master/>`_ library for all HTTP requests. This library is licensed under the `Apache License, Version 2.0 <http://www.apache.org/licenses/LICENSE-2.0>`_.


