# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from forumsentry_api.api_client import ApiClient


class PoliciesftpPoliciesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_or_update_policy(self, id, **kwargs):  # noqa: E501
        """creates or updates the FTP Policy  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.create_or_update_policy(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :param str comment:
        :param str description:
        :param bool enabled:
        :param int end_pasv_port:
        :param str get_compression_mode:
        :param str get_pgp_policy:
        :param str interface:
        :param str ip:
        :param str listener_ftps_auth_mode:
        :param str listener_ftps_mode:
        :param bool listener_ssl_enabled:
        :param str listener_ssl_initiation_policy:
        :param str listener_ssl_termination_policy:
        :param str name:
        :param bool passv_ip_override:
        :param str pasv_ip:
        :param int port:
        :param bool prevent_user_host_syntax:
        :param bool process_as_xml:
        :param str put_compression_mode:
        :param str put_pgp_policy:
        :param int read_timeout_millis:
        :param str remote_ftps_auth_mode:
        :param str remote_ftps_mode:
        :param int remote_port:
        :param str remote_server:
        :param str remote_server2:
        :param bool remote_ssl_enabled:
        :param str remote_ssl_initiation_policy:
        :param str remote_ssl_termination_policy:
        :param int start_pasv_port:
        :param bool use_device_ip:
        :param bool use_pasv_ip:
        :param str user_policy_rule:
        :return: FtpPolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.create_or_update_policy_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.create_or_update_policy_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def create_or_update_policy_with_http_info(self, id, **kwargs):  # noqa: E501
        """creates or updates the FTP Policy  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.create_or_update_policy_with_http_info(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :param str comment:
        :param str description:
        :param bool enabled:
        :param int end_pasv_port:
        :param str get_compression_mode:
        :param str get_pgp_policy:
        :param str interface:
        :param str ip:
        :param str listener_ftps_auth_mode:
        :param str listener_ftps_mode:
        :param bool listener_ssl_enabled:
        :param str listener_ssl_initiation_policy:
        :param str listener_ssl_termination_policy:
        :param str name:
        :param bool passv_ip_override:
        :param str pasv_ip:
        :param int port:
        :param bool prevent_user_host_syntax:
        :param bool process_as_xml:
        :param str put_compression_mode:
        :param str put_pgp_policy:
        :param int read_timeout_millis:
        :param str remote_ftps_auth_mode:
        :param str remote_ftps_mode:
        :param int remote_port:
        :param str remote_server:
        :param str remote_server2:
        :param bool remote_ssl_enabled:
        :param str remote_ssl_initiation_policy:
        :param str remote_ssl_termination_policy:
        :param int start_pasv_port:
        :param bool use_device_ip:
        :param bool use_pasv_ip:
        :param str user_policy_rule:
        :return: FtpPolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'comment', 'description', 'enabled', 'end_pasv_port', 'get_compression_mode', 'get_pgp_policy', 'interface', 'ip', 'listener_ftps_auth_mode', 'listener_ftps_mode', 'listener_ssl_enabled', 'listener_ssl_initiation_policy', 'listener_ssl_termination_policy', 'name', 'passv_ip_override', 'pasv_ip', 'port', 'prevent_user_host_syntax', 'process_as_xml', 'put_compression_mode', 'put_pgp_policy', 'read_timeout_millis', 'remote_ftps_auth_mode', 'remote_ftps_mode', 'remote_port', 'remote_server', 'remote_server2', 'remote_ssl_enabled', 'remote_ssl_initiation_policy', 'remote_ssl_termination_policy', 'start_pasv_port', 'use_device_ip', 'use_pasv_ip', 'user_policy_rule']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_or_update_policy" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `create_or_update_policy`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'comment' in params:
            form_params.append(('comment', params['comment']))  # noqa: E501
        if 'description' in params:
            form_params.append(('description', params['description']))  # noqa: E501
        if 'enabled' in params:
            form_params.append(('enabled', params['enabled']))  # noqa: E501
        if 'end_pasv_port' in params:
            form_params.append(('endPasvPort', params['end_pasv_port']))  # noqa: E501
        if 'get_compression_mode' in params:
            form_params.append(('getCompressionMode', params['get_compression_mode']))  # noqa: E501
        if 'get_pgp_policy' in params:
            form_params.append(('getPgpPolicy', params['get_pgp_policy']))  # noqa: E501
        if 'interface' in params:
            form_params.append(('interface', params['interface']))  # noqa: E501
        if 'ip' in params:
            form_params.append(('ip', params['ip']))  # noqa: E501
        if 'listener_ftps_auth_mode' in params:
            form_params.append(('listenerFtpsAuthMode', params['listener_ftps_auth_mode']))  # noqa: E501
        if 'listener_ftps_mode' in params:
            form_params.append(('listenerFtpsMode', params['listener_ftps_mode']))  # noqa: E501
        if 'listener_ssl_enabled' in params:
            form_params.append(('listenerSslEnabled', params['listener_ssl_enabled']))  # noqa: E501
        if 'listener_ssl_initiation_policy' in params:
            form_params.append(('listenerSslInitiationPolicy', params['listener_ssl_initiation_policy']))  # noqa: E501
        if 'listener_ssl_termination_policy' in params:
            form_params.append(('listenerSslTerminationPolicy', params['listener_ssl_termination_policy']))  # noqa: E501
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'passv_ip_override' in params:
            form_params.append(('passvIpOverride', params['passv_ip_override']))  # noqa: E501
        if 'pasv_ip' in params:
            form_params.append(('pasvIp', params['pasv_ip']))  # noqa: E501
        if 'port' in params:
            form_params.append(('port', params['port']))  # noqa: E501
        if 'prevent_user_host_syntax' in params:
            form_params.append(('preventUserHostSyntax', params['prevent_user_host_syntax']))  # noqa: E501
        if 'process_as_xml' in params:
            form_params.append(('processAsXml', params['process_as_xml']))  # noqa: E501
        if 'put_compression_mode' in params:
            form_params.append(('putCompressionMode', params['put_compression_mode']))  # noqa: E501
        if 'put_pgp_policy' in params:
            form_params.append(('putPgpPolicy', params['put_pgp_policy']))  # noqa: E501
        if 'read_timeout_millis' in params:
            form_params.append(('readTimeoutMillis', params['read_timeout_millis']))  # noqa: E501
        if 'remote_ftps_auth_mode' in params:
            form_params.append(('remoteFtpsAuthMode', params['remote_ftps_auth_mode']))  # noqa: E501
        if 'remote_ftps_mode' in params:
            form_params.append(('remoteFtpsMode', params['remote_ftps_mode']))  # noqa: E501
        if 'remote_port' in params:
            form_params.append(('remotePort', params['remote_port']))  # noqa: E501
        if 'remote_server' in params:
            form_params.append(('remoteServer', params['remote_server']))  # noqa: E501
        if 'remote_server2' in params:
            form_params.append(('remoteServer', params['remote_server2']))  # noqa: E501
        if 'remote_ssl_enabled' in params:
            form_params.append(('remoteSslEnabled', params['remote_ssl_enabled']))  # noqa: E501
        if 'remote_ssl_initiation_policy' in params:
            form_params.append(('remoteSslInitiationPolicy', params['remote_ssl_initiation_policy']))  # noqa: E501
        if 'remote_ssl_termination_policy' in params:
            form_params.append(('remoteSslTerminationPolicy', params['remote_ssl_termination_policy']))  # noqa: E501
        if 'start_pasv_port' in params:
            form_params.append(('startPasvPort', params['start_pasv_port']))  # noqa: E501
        if 'use_device_ip' in params:
            form_params.append(('useDeviceIp', params['use_device_ip']))  # noqa: E501
        if 'use_pasv_ip' in params:
            form_params.append(('usePasvIp', params['use_pasv_ip']))  # noqa: E501
        if 'user_policy_rule' in params:
            form_params.append(('userPolicyRule', params['user_policy_rule']))  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/policies/ftpPolicies/{id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FtpPolicy',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_policy(self, name, **kwargs):  # noqa: E501
        """creates a new FTP Policy  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.create_policy(name, async=True)
        >>> result = thread.get()

        :param async bool
        :param str name: (required)
        :param str comment:
        :param str description:
        :param bool enabled:
        :param int end_pasv_port:
        :param str get_compression_mode:
        :param str get_pgp_policy:
        :param str interface:
        :param str ip:
        :param str listener_ftps_auth_mode:
        :param str listener_ftps_mode:
        :param bool listener_ssl_enabled:
        :param str listener_ssl_initiation_policy:
        :param str listener_ssl_termination_policy:
        :param bool passv_ip_override:
        :param str pasv_ip:
        :param int port:
        :param bool prevent_user_host_syntax:
        :param bool process_as_xml:
        :param str put_compression_mode:
        :param str put_pgp_policy:
        :param int read_timeout_millis:
        :param str remote_ftps_auth_mode:
        :param str remote_ftps_mode:
        :param int remote_port:
        :param str remote_server:
        :param str remote_server2:
        :param bool remote_ssl_enabled:
        :param str remote_ssl_initiation_policy:
        :param str remote_ssl_termination_policy:
        :param int start_pasv_port:
        :param bool use_device_ip:
        :param bool use_pasv_ip:
        :param str user_policy_rule:
        :return: FtpPolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.create_policy_with_http_info(name, **kwargs)  # noqa: E501
        else:
            (data) = self.create_policy_with_http_info(name, **kwargs)  # noqa: E501
            return data

    def create_policy_with_http_info(self, name, **kwargs):  # noqa: E501
        """creates a new FTP Policy  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.create_policy_with_http_info(name, async=True)
        >>> result = thread.get()

        :param async bool
        :param str name: (required)
        :param str comment:
        :param str description:
        :param bool enabled:
        :param int end_pasv_port:
        :param str get_compression_mode:
        :param str get_pgp_policy:
        :param str interface:
        :param str ip:
        :param str listener_ftps_auth_mode:
        :param str listener_ftps_mode:
        :param bool listener_ssl_enabled:
        :param str listener_ssl_initiation_policy:
        :param str listener_ssl_termination_policy:
        :param bool passv_ip_override:
        :param str pasv_ip:
        :param int port:
        :param bool prevent_user_host_syntax:
        :param bool process_as_xml:
        :param str put_compression_mode:
        :param str put_pgp_policy:
        :param int read_timeout_millis:
        :param str remote_ftps_auth_mode:
        :param str remote_ftps_mode:
        :param int remote_port:
        :param str remote_server:
        :param str remote_server2:
        :param bool remote_ssl_enabled:
        :param str remote_ssl_initiation_policy:
        :param str remote_ssl_termination_policy:
        :param int start_pasv_port:
        :param bool use_device_ip:
        :param bool use_pasv_ip:
        :param str user_policy_rule:
        :return: FtpPolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name', 'comment', 'description', 'enabled', 'end_pasv_port', 'get_compression_mode', 'get_pgp_policy', 'interface', 'ip', 'listener_ftps_auth_mode', 'listener_ftps_mode', 'listener_ssl_enabled', 'listener_ssl_initiation_policy', 'listener_ssl_termination_policy', 'passv_ip_override', 'pasv_ip', 'port', 'prevent_user_host_syntax', 'process_as_xml', 'put_compression_mode', 'put_pgp_policy', 'read_timeout_millis', 'remote_ftps_auth_mode', 'remote_ftps_mode', 'remote_port', 'remote_server', 'remote_server2', 'remote_ssl_enabled', 'remote_ssl_initiation_policy', 'remote_ssl_termination_policy', 'start_pasv_port', 'use_device_ip', 'use_pasv_ip', 'user_policy_rule']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_policy" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'name' is set
        if ('name' not in params or
                params['name'] is None):
            raise ValueError("Missing the required parameter `name` when calling `create_policy`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'name' in params:
            form_params.append(('name', params['name']))  # noqa: E501
        if 'comment' in params:
            form_params.append(('comment', params['comment']))  # noqa: E501
        if 'description' in params:
            form_params.append(('description', params['description']))  # noqa: E501
        if 'enabled' in params:
            form_params.append(('enabled', params['enabled']))  # noqa: E501
        if 'end_pasv_port' in params:
            form_params.append(('endPasvPort', params['end_pasv_port']))  # noqa: E501
        if 'get_compression_mode' in params:
            form_params.append(('getCompressionMode', params['get_compression_mode']))  # noqa: E501
        if 'get_pgp_policy' in params:
            form_params.append(('getPgpPolicy', params['get_pgp_policy']))  # noqa: E501
        if 'interface' in params:
            form_params.append(('interface', params['interface']))  # noqa: E501
        if 'ip' in params:
            form_params.append(('ip', params['ip']))  # noqa: E501
        if 'listener_ftps_auth_mode' in params:
            form_params.append(('listenerFtpsAuthMode', params['listener_ftps_auth_mode']))  # noqa: E501
        if 'listener_ftps_mode' in params:
            form_params.append(('listenerFtpsMode', params['listener_ftps_mode']))  # noqa: E501
        if 'listener_ssl_enabled' in params:
            form_params.append(('listenerSslEnabled', params['listener_ssl_enabled']))  # noqa: E501
        if 'listener_ssl_initiation_policy' in params:
            form_params.append(('listenerSslInitiationPolicy', params['listener_ssl_initiation_policy']))  # noqa: E501
        if 'listener_ssl_termination_policy' in params:
            form_params.append(('listenerSslTerminationPolicy', params['listener_ssl_termination_policy']))  # noqa: E501
        if 'passv_ip_override' in params:
            form_params.append(('passvIpOverride', params['passv_ip_override']))  # noqa: E501
        if 'pasv_ip' in params:
            form_params.append(('pasvIp', params['pasv_ip']))  # noqa: E501
        if 'port' in params:
            form_params.append(('port', params['port']))  # noqa: E501
        if 'prevent_user_host_syntax' in params:
            form_params.append(('preventUserHostSyntax', params['prevent_user_host_syntax']))  # noqa: E501
        if 'process_as_xml' in params:
            form_params.append(('processAsXml', params['process_as_xml']))  # noqa: E501
        if 'put_compression_mode' in params:
            form_params.append(('putCompressionMode', params['put_compression_mode']))  # noqa: E501
        if 'put_pgp_policy' in params:
            form_params.append(('putPgpPolicy', params['put_pgp_policy']))  # noqa: E501
        if 'read_timeout_millis' in params:
            form_params.append(('readTimeoutMillis', params['read_timeout_millis']))  # noqa: E501
        if 'remote_ftps_auth_mode' in params:
            form_params.append(('remoteFtpsAuthMode', params['remote_ftps_auth_mode']))  # noqa: E501
        if 'remote_ftps_mode' in params:
            form_params.append(('remoteFtpsMode', params['remote_ftps_mode']))  # noqa: E501
        if 'remote_port' in params:
            form_params.append(('remotePort', params['remote_port']))  # noqa: E501
        if 'remote_server' in params:
            form_params.append(('remoteServer', params['remote_server']))  # noqa: E501
        if 'remote_server2' in params:
            form_params.append(('remoteServer', params['remote_server2']))  # noqa: E501
        if 'remote_ssl_enabled' in params:
            form_params.append(('remoteSslEnabled', params['remote_ssl_enabled']))  # noqa: E501
        if 'remote_ssl_initiation_policy' in params:
            form_params.append(('remoteSslInitiationPolicy', params['remote_ssl_initiation_policy']))  # noqa: E501
        if 'remote_ssl_termination_policy' in params:
            form_params.append(('remoteSslTerminationPolicy', params['remote_ssl_termination_policy']))  # noqa: E501
        if 'start_pasv_port' in params:
            form_params.append(('startPasvPort', params['start_pasv_port']))  # noqa: E501
        if 'use_device_ip' in params:
            form_params.append(('useDeviceIp', params['use_device_ip']))  # noqa: E501
        if 'use_pasv_ip' in params:
            form_params.append(('usePasvIp', params['use_pasv_ip']))  # noqa: E501
        if 'user_policy_rule' in params:
            form_params.append(('userPolicyRule', params['user_policy_rule']))  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/policies/ftpPolicies', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FtpPolicy',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_policy_copy(self, id, new_id, **kwargs):  # noqa: E501
        """creates a copy of the FTP Policy  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.create_policy_copy(id, new_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :param str new_id: (required)
        :return: FtpPolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.create_policy_copy_with_http_info(id, new_id, **kwargs)  # noqa: E501
        else:
            (data) = self.create_policy_copy_with_http_info(id, new_id, **kwargs)  # noqa: E501
            return data

    def create_policy_copy_with_http_info(self, id, new_id, **kwargs):  # noqa: E501
        """creates a copy of the FTP Policy  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.create_policy_copy_with_http_info(id, new_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :param str new_id: (required)
        :return: FtpPolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'new_id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_policy_copy" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `create_policy_copy`")  # noqa: E501
        # verify the required parameter 'new_id' is set
        if ('new_id' not in params or
                params['new_id'] is None):
            raise ValueError("Missing the required parameter `new_id` when calling `create_policy_copy`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'new_id' in params:
            query_params.append(('newId', params['new_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/policies/ftpPolicies/{id}/copy', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FtpPolicy',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def export_fsg(self, id, password, **kwargs):  # noqa: E501
        """exports an fsg based on this policy to a file  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.export_fsg(id, password, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :param str password: (required)
        :param str agent:
        :return: JavaIoOutputStream
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.export_fsg_with_http_info(id, password, **kwargs)  # noqa: E501
        else:
            (data) = self.export_fsg_with_http_info(id, password, **kwargs)  # noqa: E501
            return data

    def export_fsg_with_http_info(self, id, password, **kwargs):  # noqa: E501
        """exports an fsg based on this policy to a file  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.export_fsg_with_http_info(id, password, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :param str password: (required)
        :param str agent:
        :return: JavaIoOutputStream
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'password', 'agent']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method export_fsg" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `export_fsg`")  # noqa: E501
        # verify the required parameter 'password' is set
        if ('password' not in params or
                params['password'] is None):
            raise ValueError("Missing the required parameter `password` when calling `export_fsg`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'agent' in params:
            query_params.append(('agent', params['agent']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'password' in params:
            form_params.append(('password', params['password']))  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/octet-stream'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/policies/ftpPolicies/{id}/fsg', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JavaIoOutputStream',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_policy(self, id, **kwargs):  # noqa: E501
        """gets the FTP Policy  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_policy(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :return: FtpPolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.get_policy_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_policy_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def get_policy_with_http_info(self, id, **kwargs):  # noqa: E501
        """gets the FTP Policy  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_policy_with_http_info(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :return: FtpPolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_policy" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `get_policy`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/policies/ftpPolicies/{id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FtpPolicy',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_policy_list(self, **kwargs):  # noqa: E501
        """returns a list of policies  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_policy_list(async=True)
        >>> result = thread.get()

        :param async bool
        :return: PolicyList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.get_policy_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_policy_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_policy_list_with_http_info(self, **kwargs):  # noqa: E501
        """returns a list of policies  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_policy_list_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :return: PolicyList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_policy_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/policies/ftpPolicies', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PolicyList',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def remove_policy(self, id, **kwargs):  # noqa: E501
        """deletes the policy  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remove_policy(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.remove_policy_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.remove_policy_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def remove_policy_with_http_info(self, id, **kwargs):  # noqa: E501
        """deletes the policy  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remove_policy_with_http_info(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method remove_policy" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `remove_policy`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/policies/ftpPolicies/{id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def transfer_fsg(self, id, agent_group, **kwargs):  # noqa: E501
        """transfers an fsg based on this policy to the specified agent group  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.transfer_fsg(id, agent_group, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :param str agent_group: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.transfer_fsg_with_http_info(id, agent_group, **kwargs)  # noqa: E501
        else:
            (data) = self.transfer_fsg_with_http_info(id, agent_group, **kwargs)  # noqa: E501
            return data

    def transfer_fsg_with_http_info(self, id, agent_group, **kwargs):  # noqa: E501
        """transfers an fsg based on this policy to the specified agent group  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.transfer_fsg_with_http_info(id, agent_group, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :param str agent_group: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'agent_group']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method transfer_fsg" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `transfer_fsg`")  # noqa: E501
        # verify the required parameter 'agent_group' is set
        if ('agent_group' not in params or
                params['agent_group'] is None):
            raise ValueError("Missing the required parameter `agent_group` when calling `transfer_fsg`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'agent_group' in params:
            query_params.append(('agentGroup', params['agent_group']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/policies/ftpPolicies/{id}/transfer', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
